[package]
name = "nw-pckt-fwd"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.35"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.5"
