[package]
name = "nw-pckt-fwd"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
#build = "./custom_task/generate_compile_time_info.rs"
[dependencies]
pnet = "0.35"
tokio = { version = "1.42.0", features = ["full", "tracing"] }
tokio-util = "0.7.13"
clap = { version = "4.5.26", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"
lazy_static = "1.5.0"
syslog = "7.0.0"
tracing = { version = "0.1.41", optional = true }
tracing-subscriber = { version = "0.3.19", optional = true }
console-subscriber = { version = "0.4.1", optional = true }

[build-dependencies]
chrono = "0.4.39"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[features]
# Feature to enable tokio-console
tokio-console = ["console-subscriber"]
