name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Nix flake check
      run: |
        nix flake check